window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\ASUS\\AppData\\Roaming",
  "asl.log": "Destination=file",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_6972_HAZYEEFQYSTJWUYB",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "CYBERSPACE",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "CUDA_PATH": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8",
  "CUDA_PATH_V11_8": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\Windows\\notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\ASUS\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\ASUS",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\ASUS",
  "INIT_CWD": "C:\\Users\\ASUS\\Documents\\WebDevProjects\\cashien",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\ASUS\\AppData\\Local",
  "LOGONSERVER": "\\\\CYBERSPACE",
  "MinGW": "C:\\MinGW\\bin",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\ASUS\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\ASUS\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\ASUS\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\ASUS\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\ASUS\\Documents\\WebDevProjects\\cashien",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_npm_version": "10.2.4",
  "npm_config_prefix": "C:\\Users\\ASUS\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\ASUS\\.npmrc",
  "npm_config_user_agent": "npm/10.2.4 node/v20.11.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\ASUS\\Documents\\WebDevProjects\\cashien\\package.json",
  "npm_package_name": "cashien",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\ASUS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "12",
  "NVTOOLSEXT_PATH": "C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\",
  "OneDrive": "C:\\Users\\ASUS\\OneDrive",
  "OPENAI_API_KEY": "sk-abcdef1234567890abcdef1234567890abcdef12",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\ASUS\\Documents\\WebDevProjects\\cashien\\node_modules\\.bin;C:\\Users\\ASUS\\Documents\\WebDevProjects\\node_modules\\.bin;C:\\Users\\ASUS\\Documents\\node_modules\\.bin;C:\\Users\\ASUS\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\ASUS\\Documents\\WebDevProjects\\cashien\\node_modules\\.bin;C:\\Users\\ASUS\\Documents\\WebDevProjects\\node_modules\\.bin;C:\\Users\\ASUS\\Documents\\node_modules\\.bin;C:\\Users\\ASUS\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.3.0\\;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\extras\\CUPTI\\lib64;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\extras\\CUPTI\\include;C:\\tools\\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\\bin;C:\\tools\\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\\include;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\MinGW\\bin;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\python.exe;C:\\Program Files\\GitHub CLI\\;C:\\Users\\ASUS\\.cargo\\bin;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\ASUS\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\ASUS\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\ASUS\\AppData\\Roaming\\npm;C:\\Users\\ASUS\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-7.0-full_build\\bin;",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 165 Stepping 2, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "a502",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\ASUS\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "REACT_APP_BH_DEV": "http://192.168.0.3:8000",
  "REACT_APP_BH_PROD": "https://yueh33455.pythonanywhere.com",
  "REACT_APP_COMPNAME": "Cashien",
  "REACT_APP_ENV": "PROD",
  "REACT_APP_WS_DEV": "ws://192.168.0.3:8080",
  "REACT_APP_WS_PROD": "wss://outbound-wogo.onrender.com",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\ASUS\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.100.2",
  "TMP": "C:\\Users\\ASUS\\AppData\\Local\\Temp",
  "USERDOMAIN": "CYBERSPACE",
  "USERDOMAIN_ROAMINGPROFILE": "CYBERSPACE",
  "USERNAME": "ASUS",
  "USERPROFILE": "C:\\Users\\ASUS",
  "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\ASUS\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\ASUS\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-bcb98efee6-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\Windows"
};